name: Testing project
on: push
jobs:
  install_stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Install checkout
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependences
        run: npm ci
      - name: Run Test
        run: npm test
  deploy:
    needs: install_stuff
    runs-on: ubuntu-latest
    steps:
      - name: Install checkout
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependences
        run: npm ci
      - name: Run Test
        run: npm test
      - name: Run build
        run: npm run build
      - name: deploying
        run: echo "deploy...."